### ISSUE TITLE
is mask-head cascaded too?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [zhaoweicai/Detectron-Cascade-RCNN#11]
hi @zhaoweicai 
do u do cascaded-heads for mask branch?

**Comment by zhaoweicai** [comment]
No, mask branch in only on the last cascade stage.

**Comment by zimenglan-sysu-512** [comment]
thanks,
i have another question that does the second and third stage take the heuristic 1:3 samping policy for proposals/rois like the fast-rcnn?

**Comment by zhaoweicai** [comment]
No, quoted from the paper, the 2nd and 3rd stage use all outputs from previous stages, and don't use the 1:3 ratio.

**Comment by zimenglan-sysu-512** [comment]
hi @zhaoweicai 
i want to ask u one more question, have u tried OHEM for cascaded-rcnn?
thanks
