### ISSUE TITLE
INFO loader.py: 113: Stopping mini-batch loading thread,can you tell me why ?

### ISSUE THREAD

**Issue by larsoncs** [zhaoweicai/Detectron-Cascade-RCNN#8]
CRITICAL train.py:  98: roi_data_loader failed
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread

**Comment by zhaoweicai** [comment]
The training is stopped. Maybe there are some errors of your run. Can't tell much from the log you provide.
